# Generated by Django 4.0.5 on 2022-06-25 09:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('video_id', models.CharField(max_length=255, unique=True)),
                ('thumbnail', models.URLField()),
                ('publish_time', models.DateTimeField()),
                ('channel_title', models.CharField(max_length=255)),
            ],
        ),
    ]
