# Generated by Django 4.0.5 on 2022-06-25 17:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('YT', 'Yt_Key_Index'), ('None', 'none')], max_length=10)),
                ('index', models.IntegerField(default=0)),
            ],
        ),
    ]
